MVP-23466: adding config variables to determine whether to route the …
PropelPLM/propel-document-old pull request #3
Opened 2023-05-16 17:39 UTC by prateekshal

…request to Java service. Also uses config variable to determine which Java service to use

2023-05-23 16:31 UTC, danielxji6 requested changes

2023-05-23 16:31 UTC, danielxji6 commented on api/v2/lib/Watermark.js
> +      req.on("error", (e) => {
nit: better to use `'` throughout the js file.

2023-05-24 18:58 UTC, prateekshal commented on api/v2/lib/Watermark.js
> +          console.log("Java request sent successfully " + data);
The data isn nothing but a string "pass" as Java adds the request to worker dyno's queue.

2023-05-24 20:44 UTC, danielxji6 approved these changes

2023-05-24 20:56 UTC, merged